# -*- coding: utf-8 -*-
"""Loan_payback_regressor_streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Q6T2JFl1CRA2OHrfMIt5tW8Psi21K1u
"""

import streamlit as st
import pandas as pd
import joblib # Import joblib for loading the model
import numpy as np
from sklearn.preprocessing import PolynomialFeatures, StandardScaler # Ensure these are imported if not already
import altair as alt # Import altair for custom chart colors

# Set page config and inject custom CSS for background color
st.set_page_config(page_title="💰 Bucknell Lending Club: Loan Outcome Score", layout="centered")
st.markdown("""
    <style>
    .stApp {
        background-color: #FFF3E0; /* Light orange color */
    }
    </style>
    """, unsafe_allow_html=True)

# Open the file and load the model, poly, scaler, and training_columns
file_to_load = 'loan_model_regressor.pkl'
poly_file = 'poly.pkl'
scaler_file = 'scaler.pkl'
training_columns_file = 'training_predictors_columns.pkl'

try:
    with open(file_to_load, 'rb') as file:
        loaded_model = joblib.load(file)
    with open(poly_file, 'rb') as file:
        poly = joblib.load(file)
    with open(scaler_file, 'rb') as file:
        scaler = joblib.load(file)
    with open(training_columns_file, 'rb') as file:
        training_predictors_columns = joblib.load(file)
    st.success("Model and preprocessing objects loaded successfully!")
except FileNotFoundError as e:
    st.error(f"Error loading file: {e}. Please ensure '{e.filename}' exists in the environment.")
    st.stop() # Stop the app if essential files are missing
except Exception as e:
    st.error(f"An unexpected error occurred during loading: {e}")
    st.stop()


# --- Streamlit UI ---

# Bucknell Colors
BUCKNELL_BLUE = "#002856"
BUCKNELL_ORANGE = "#D36C2F"

st.markdown(f"<h1 style='text-align: center; color: {BUCKNELL_BLUE};'>💰 Bucknell Lending Club: Loan Outcome Score Predictor</h1>", unsafe_allow_html=True)
st.markdown(f"<p style='text-align: center; color: {BUCKNELL_BLUE};'>Enter a potential loan customer's details to predict their Ret_PESS score.</p>", unsafe_allow_html=True)

# Create two columns for input
col1, col2 = st.columns(2)

with col1:
    st.header("Loan Details")
    loan_amnt = st.number_input("Loan Amount", min_value=0.0, max_value=50000.0, value=10000.0, step=100.0)
    funded_amnt = st.number_input("Funded Amount", min_value=0.0, max_value=50000.0, value=10000.0, step=100.0)
    int_rate = st.slider("Interest Rate (%)", min_value=0.0, max_value=30.0, value=15.0, step=0.1)
    installment = st.number_input("Installment", min_value=0.0, max_value=2000.0, value=300.0, step=10.0)
    term_num = st.selectbox("Term (months)", options=[36, 60], index=0)
    purpose = st.selectbox("Purpose", options=['car', 'credit_card', 'debt_consolidation', 'educational', 'home_improvement', 'house', 'major_purchase', 'medical', 'moving', 'other', 'renewable_energy', 'small_business', 'vacation', 'wedding'], index=2)
    grade = st.selectbox("Grade", options=['A', 'B', 'C', 'D', 'E', 'F', 'G'], index=1)

with col2:
    st.header("Borrower Details")
    income = st.slider("Annual Income", 20000, 1000000, 80000)
    dti = st.slider("Debt-to-Income Ratio", 0, 40, 10)
    fico = st.slider("FICO Score", 300, 850, 650)
    home_ownership = st.selectbox("Home Ownership", options=['MORTGAGE', 'OWN', 'RENT', 'OTHER', 'NONE'], index=1)
    emp_length = st.selectbox("Employment Length", options=['< 1 year', '1 year', '2 years', '3 years', '4 years', '5 years', '6 years', '7 years', '8 years', '9 years', '10+ years'], index=10)
    verification_status = st.selectbox("Verification Status", options=['Not Verified', 'Source Verified', 'Verified'], index=1)
    delinq_2yrs = st.number_input("Delinquencies in Last 2 Years", min_value=0, max_value=20, value=0)
    open_acc = st.number_input("Number of Open Credit Lines", min_value=0, max_value=50, value=5)
    pub_rec = st.number_input("Number of Public Record Derogatories", min_value=0, max_value=20, value=0)
    revol_bal = st.number_input("Revolving Balance", min_value=0.0, max_value=100000.0, value=10000.0, step=100.0)
    revol_util = st.slider("Revolving Line Utilization (%)", min_value=0.0, max_value=100.0, value=50.0, step=0.1)

# Prediction
if st.button("Predict Ret_PESS Score"):
    raw_customer_data_dict = {
        'loan_amnt': loan_amnt,
        'funded_amnt': funded_amnt,
        'int_rate': int_rate,
        'installment': installment,
        'dti': dti,
        'delinq_2yrs': delinq_2yrs,
        'open_acc': open_acc,
        'pub_rec': pub_rec,
        'fico_range_high': fico,
        'fico_range_low': fico,
        'revol_bal': revol_bal,
        'revol_util': revol_util,
        'term_num': term_num,
        'annual_inc': income,
        'grade': grade,
        'emp_length': emp_length,
        'home_ownership': home_ownership,
        'verification_status': verification_status,
        'purpose': purpose
    }
    new_customer_raw_df = pd.DataFrame([raw_customer_data_dict])

    # --- Apply preprocessing steps as per training code ---
    new_customer_raw_df['annual_inc'] = new_customer_raw_df['annual_inc'].replace(0, np.nan).fillna(1)
    new_customer_raw_df['log_annual_inc'] = np.log(new_customer_raw_df['annual_inc'])
    new_customer_raw_df = new_customer_raw_df.drop(columns=['annual_inc'])

    cat_cols = ['grade', 'emp_length', 'home_ownership', 'verification_status', 'purpose']
    customer_encoded_df = pd.get_dummies(new_customer_raw_df, columns=cat_cols, prefix_sep='_', drop_first=True)

    processed_df_aligned = customer_encoded_df.reindex(columns=training_predictors_columns, fill_value=0)

    user_data_poly = poly.transform(processed_df_aligned)
    user_data_scaled = scaler.transform(user_data_poly)

    # Make Prediction (regression model)
    predicted_value = loaded_model.predict(user_data_scaled)[0]

    st.markdown(f"<h3 style='color: {BUCKNELL_BLUE};'>Predicted Ret_PESS Score: **{predicted_value:.2f}**</h3>", unsafe_allow_html=True)

    # --- Ret_PESS Visualization ---
    st.subheader("Ret_PESS Score Position")

    # Define a plausible range for Ret_PESS (adjust these values based on your model's actual output range)
    min_ret_pess = -33.1 # Example min, adjust as per your model's actual output range
    max_ret_pess = 16.0  # Example max, adjust as per your model's actual output range

    # Ensure the predicted value is within the defined range for display
    display_value = max(min_ret_pess, min(max_ret_pess, predicted_value))

    # Create a base chart for the range line
    base_chart = alt.Chart(pd.DataFrame({'x': [min_ret_pess, max_ret_pess]})).mark_line(
        strokeWidth=5,
        color=BUCKNELL_BLUE
    ).encode(
        x=alt.X('x', type='quantitative', title='Ret_PESS Score', axis=alt.Axis(values=[min_ret_pess, 0, max_ret_pess], format='.1f'))
    )

    # Create a chart for the predicted value as a point
    predicted_point_chart = alt.Chart(pd.DataFrame({'predicted_value': [display_value]})).mark_point(
        size=200,
        color=BUCKNELL_ORANGE,
        filled=True,
        shape='diamond'
    ).encode(
        x='predicted_value'
    )

    # Add text labels for min, max, and predicted values
    min_text = alt.Chart(pd.DataFrame({'x': [min_ret_pess], 'text': [f'{min_ret_pess:.1f}']})).mark_text(
        align='right', baseline='bottom', dx=-5, dy=20, color=BUCKNELL_BLUE
    ).encode(x='x', text='text')

    max_text = alt.Chart(pd.DataFrame({'x': [max_ret_pess], 'text': [f'{max_ret_pess:.1f}']})).mark_text(
        align='left', baseline='bottom', dx=5, dy=20, color=BUCKNELL_BLUE
    ).encode(x='x', text='text')

    predicted_text = alt.Chart(pd.DataFrame({'x': [display_value], 'text': [f'{display_value:.2f}']})).mark_text(
        align='center', baseline='top', dy=-20, color=BUCKNELL_ORANGE,
        fontSize=14, fontWeight='bold'
    ).encode(x='x', text='text')


    # Combine all charts
    final_chart = (base_chart + predicted_point_chart + min_text + max_text + predicted_text).properties(
        title='Predicted Ret_PESS Score on a Scale',
        height=200, # Increased height for better visibility
        width=700 # Set a fixed width
    )

    st.altair_chart(final_chart)

st.markdown("---")